# illumos gitlab-runner maintained by @hww3
build_illumos:
  only:
    - master@SoftEther/SoftEtherVPN
  tags: 
    - illumos
  script:
    - git submodule init && git submodule update
    - CMAKE_FLAGS="-DCMAKE_PREFIX_PATH=/opt/local -DCMAKE_CXX_FLAGS=-m64 -DCMAKE_C_FLAGS=-m64" ./configure
    - gmake -C build

